### ISSUE TITLE
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

### ISSUE THREAD

**Issue by luismgg** [ohle/Swingspector#30]
I get this error on Windows 11, it seems to be unable to parse the path where swag-1.2.1.jar is located.
I'm using Java 11 Zulu.

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Non-Bundled Plugins:
    de.eudaemon.ideaswag (2.0.1)
Kotlin: 231-1.8.20-IJ8109.175

`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:515)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:527)
Caused by: java.nio.file.NoSuchFileException: C
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1843)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1212)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:258)
	at de.eudaemon.swag.SwagAgent$Options.parse(SwagAgent.java:89)
	at de.eudaemon.swag.SwagAgent.premain(SwagAgent.java:51)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at e:\jenkins\tmp\workspace\build\src\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

Process finished with exit code 1
`
![image](https://user-images.githubusercontent.com/19175871/229783296-1544ab9f-d8cd-42c8-8a18-97e25f2fd881.png)
![image](https://user-images.githubusercontent.com/19175871/229783410-e8dba295-8cb1-483e-a5cc-a1f054f79088.png)

**Comment by ohle** [comment]
Yep, I've never actually tested this on windows. I've (hopefully) fixed it in [the agent](https://github.com/ohle/swag). Will build a new release now.

**Comment by ohle** [comment]
@luismgg can you try 2.0.2? You can manually install from [here](https://github.com/ohle/Swingspector/releases/download/v2.0.2/Swingspector-2.0.2.zip) or wait one or two days for Jetbrains to approve the update in the marketplace.

**Comment by luismgg** [comment]
It's working now. Thanks
